LIB = png

CSRCS =						\
	png						\
	pngset					\
	pngget					\
	pngrutil				\
	pngtrans				\
	pngwutil				\
	pngread					\
	pngrio					\
	pngwio					\
	pngwrite				\
	pngrtran				\
	pngwtran				\
	pngmem					\
	pngerror				\
	pngpread				\



ifndef MF_ROOT
export MF_ROOT := $(subst /bigworld/src/lib/$(LIB),,$(CURDIR))
endif

include $(MF_ROOT)/bigworld/src/build/common.mak
