#define IDD_UAL                         2000
#define IDD_UALNAME                     2001
#define IDB_UALMAGNIFIER                2100
#define IDB_UALSHOWFILTERS              2101
#define IDB_UALHIDEFILTERS              2102
#define IDB_UALSEARCHCLOSE              2103
#define IDI_UALFOLDER                   2104
#define IDI_UALFOLDERSEL                2105
#define IDI_UALFILE                     2106
#define IDB_UALSHOWFILTERSA             2107
#define IDB_UALHIDEFILTERSA             2108
#define IDI_UALFILESEL                  2109
#define IDI_UALREFRESH                  2110
#define IDI_UALLAYOUT                   2111
#define IDC_UALSEARCHBK					2200
#define IDC_UALTREE                     2204
#define IDC_UALLIST                     2205
#define IDC_UALSTATUS					2206
#define IDC_UALREFRESH                  2207
#define IDC_UALLAYOUT                   2208
#define IDC_UALNAMELONG                 2209
#define IDC_UALNAMESHORT                2210
