LIB =	math

SRCS =				\
	boundbox		\
	ema				\
	matrix			\
	planeeq			\
	portal2d		\
	quat			\
	vector2			\
	vector3			\
	vector4			\
	stat_watcher_creator \
	math_extra

ifndef MF_ROOT
export MF_ROOT := $(subst /bigworld/src/lib/$(LIB),,$(CURDIR))
endif

include $(MF_ROOT)/bigworld/src/build/common.mak

