//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by world_editor_app.rc
//
#define IDR_MANIFEST_LEGACY             1
#define IDR_IMP_TER_TOOLBAR             4
#define IDR_IMP_TER_TOOLBAR1            5
#define IDR_IMP_TER_DIS_TOOLBAR         5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDD_MENUVIEW                    102
#define ID_INDICATOR_MESSAGE            103
#define IDD_PROPPAGE_SMALL              104
#define ID_INDICATOR_TRIANGLES          105
#define ID_INDICATOR_SNAPS              106
#define ID_INDICATOR_POSITION           107
#define ID_INDICATOR_FRAMERATE          108
#define IDS_LARGE_IMPORT_MASK           109
#define IDR_MAINFRAME                   128
#define IDR_bigbang2TYPE                129
#define IDD_PAGE_TERRAIN                130
#define IDS_PAGE_ENTITY_CAPTION         131
#define IDR_TOOLBAR1                    132
#define IDS_PAGE_SHELL_CAPTION          133
#define IDD_PAGE_PROPERTIES             134
#define IDB_BITMAP1                     135
#define IDD_PAGE_OPTIONS                136
#define IDS_PAGE_MODEL_CAPTION          137
#define IDD_PAGE_PROJECT                138
#define IDS_PAGE_PREFAB_CAPTION         139
#define IDS_PAGE_PARTICLE_CAPTION       140
#define ID_MENU_DESELECTALL             141
#define ID_MENU_SELECTALL               142
#define ID_INDICATOR_CHUNKS             143
#define ID_MENU_SAVECAMERAPOSITION      144
#define IDS_PAGE_SPEEDTREE_CAPTION      145
#define IDS_NOLOADSKYBOX                146
#define IDS_NOLOADSKYDOME               147
#define ID_MENU_SAVETEMPLATE            148
#define IDS_NOTRESPATH                  149
#define IDS_FAILED_IMPORT_TERRAIN       150
#define IDS_EBM_ADDITIVE                151
#define IDS_EBM_SUBTRACTIVE             152
#define IDS_EBM_OVERLAY                 153
#define IDS_EBM_MIN                     154
#define IDS_EBM_MAX                     155
#define IDS_EBM_REPLACE                 156
#define IDS_LARGE_IMPORT                157
#define ID_MENU_SAVESTARTPOSITION       158
#define IDS_PAGE_LIGHT_CAPTION          159
#define IDS_PAGE_MISC_CAPTION           160
#define ID_MENU_SHOWSIDEPANEL           161
#define IDS_SHEET_MENU                  162
#define IDS_BADCODEC_IMPORT_TERRAIN     163
#define IDD_PAGE_OBJECT_MODEL_BROWSE    164
#define IDS_FILESMUSTDIFFER             165
#define IDS_NOLOADSKYGRADIENT           166
#define IDD_PAGE_TERRAIN_TEXTURE        167
#define ID_INDICATOR_MEMORYLOAD         168
#define IDD_PAGE_TERRAIN_HEIGHT         169
#define IDD_PAGE_TERRAIN_FILTER         170
#define IDD_PAGE_TERRAIN_MESH           171
#define IDD_PAGE_ERRORS                 172
#define ID_MENU_SAVEPREFAB              173
#define IDD_PAGE_SCENE                  174
#define IDR_SCENE_ICONS                 176
#define IDR_SCENE_POPUP                 177
#define ID_SCENE_POPUP_INSERT           178
#define ID_SCENE_POPUP_DELETE           179
#define ID_POPUP_RENAME                 180
#define ID_SCENE_POPUP_RENAME           181
#define ID_Menu                         182
#define ID_SCENE_POPUP_MOVESELECTIONHERE 183
#define IDB_SPLASH                      183
#define IDR_PROPERTIES_LIST_POPUP       184
#define IDR_PROPERTIES_LISTITEM_POPUP   185
#define ID_PROPERTIES_LIST_POPUP_ADDITEM 186
#define ID_PROPERTIES_LISTITEM_POPUP_REMOVEITEM 187
#define IDD_MODELESS_INFO               189
#define ID_FILE_IMPORT                  190
#define IDD_PAGE_OBJECT1                191
#define IDD_PAGE_OPTIONSHEET            192
#define ID_FILE_EXPORT                  193
#define IDD_PAGE_OPTIONS_GENERAL        194
#define IDD_PAGE_OPTIONS_GENERAL1       195
#define IDD_PAGE_OPTIONS_WEATHER        196
#define IDB_BITMAP2                     197
#define IDB_ABOUTBOX                    198
#define IDD_PAGE_OPTIONS_HISTOGRAM      199
#define IDB_BITMAP3                     200
#define IDD_DIALOG1                     202
#define IDD_SPLASH                      203
#define IDD_HTMLDIALOG                  204
#define IDR_HTML1                       205
#define IDR_KEY_CUTS                    206
#define ID_HELP_KEY_CUTS                207
#define IDD_DIALOG2                     208
#define IDD_NEWSPACE                    209
#define IDD_PLACEMENT_CTRLS             210
#define IDD_RANDNEWPRESET               211
#define IDI_ICON1                       212
#define IDI_PLACEMENT_RESET             213
#define IDI_PLACEMENT_LINK              214
#define IDI_PLACEMENT_LINKUP            215
#define IDI_ICON2                       216
#define IDI_PLACEMENT_LINKDOWN          217
#define IDD_PAGE_OPTIONS_ENVIRONMENT    218
#define IDC_HEIGHTPICKER                219
#define IDD_LIMITSLIDER                 220
#define IDD_PAGE_OBJECTS                221
#define IDD_PAGE_TERRAIN_IMPORT         222
#define IDD_RAW_IMPORT_DLG              223
#define IDR_SKYDOME_TB                  224
#define IDR_SKYDOME_DIS_TB              225
#define IDB_OPEN                        226
#define IDB_OPEND                       227
#define IDB_NEWFILE                     228
#define IDB_NEWFILED                    229
#define IDB_DUPLICATE                   230
#define IDB_DUPLICATED                  231
#define IDD_WAITDLG                     232
#define IDD_ERRORS                      233
#define IDB_RANGESLIDER                 234
#define IDD_OUT_OF_MEMORY               235
#define IDD_PAGE_CHUNK_TEXTURE          236
#define IDI_CHUNK_TEXTURE_SHOW          240
#define IDI_CHUNK_TEXTURE_TRACK         241
#define IDD_PAGE_CHUNK_WATCHER          242
#define IDI_CHUNK_TEXTURE_HIDE          243
#define IDI_CHUNK_TEXTURE_NOTRACK       244
#define IDI_PAGE_TERRAIN_LINK           246
#define IDD_CONVERTSPACE                248
#define IDD_SHADER_LOADING              249
#define IDR_IMP_MASK_TOOLBAR            250
#define IDR_IMP_MASK_DIS_TOOLBAR        251
#define IDD_RESIZEMAPS                  252
#define IDR_SKYBOXES_TB                 252
#define IDI_PAGE_TERRAIN_LINKUP         253
#define IDR_SKYBOXES_DIS_TB             253
#define IDI_PAGE_TERRAIN_LINKDOWN       254
#define IDB_EDITPROJ                    255
#define IDI_PP_3DPREVIEW_SHOW           255
#define IDB_EDITPROJD                   256
#define IDD_NOISE_SETUP                 257
#define IDB_SAVEBRUSH                   258
#define IDB_SAVEBRUSHD                  259
#define IDD_SCENE_BROWSER               260
#define IDD_UNDOWARN                    261
#define IDB_CHECK_ON                    263
#define IDD_STRING_INPUT                264
#define IDB_SEARCHMAGNIFIER_CLICK       265
#define IDD_PAGE_POST_PROCESSING        266
#define IDD_POST_PROC_CHAINS            277
#define IDD_POST_PROC_PROPERTIES        278
#define IDB_PP_NODE_DELETE              280
#define IDD_POST_PROC_CAPTIONBAR        281
#define IDI_PP_DELETE_ALL               282
#define IDB_EFFECT_NODE_BTN_OFF         287
#define IDB_EFFECT_NODE_BTN_ON          288
#define IDI_PP_LAYOUT                   289
#define IDR_WORKING_ANI                 290
#define IDI_PP_ZOOM_IN                  290
#define IDI_PP_ZOOM_OUT                 291
#define IDI_PP_NOZOOM                   292
#define IDI_PP_PROFILE_SHOW             293
#define IDI_PP_3DPREVIEW_CHECKED        294
#define IDI_PP_PROFILE_CHECKED          295
#define IDC_SELECTION_FILTER            900
#define IDC_COORDINATION_FILTER         901
#define IDC_PROPSHEET_PLACEHOLDER       1001
#define IDC_PROPSHEET_OBJECT_PLACEHOLDER 1002
#define IDC_OBJECT_ENTITY_DIR_LIST      1003
#define IDC_TERRAIN_FALLOFF_CURVE3      1004
#define IDC_TERRAIN_RELATIVEHEIGHT      1005
#define IDC_OBJECT_ENTITY_FILE_LIST     1006
#define IDC_OBJECT_ENTITY_CURRENT_DIR   1007
#define IDC_OBJECT_MODEL_CURRENT_DIR    1008
#define IDC_OBJECT_SHELL_CURRENT_DIR    1009
#define IDC_OBJECT_CURRENT_DIR          1010
#define IDC_OBJECT_DIR_LIST             1011
#define IDC_OBJECT_FILE_LIST            1012
#define IDC_LIST2                       1013
#define IDC_OBJECT_PLACE_NORMAL         1014
#define IDC_OBJECT_PLACE_ROTATED        1015
#define IDC_OBJECT_PLACE_ROTATED_SCALED 1016
#define IDC_PROPSHEET_TERRAIN_PLACEHOLDER 1017
#define IDC_TERRAIN_ALPHA_CHANNEL1      1018
#define IDC_TERRAIN_ALPHA_CHANNEL2      1019
#define IDC_TERRAIN_ALPHA_CHANNEL3      1020
#define IDC_TERRAIN_ALPHA_CHANNEL4      1021
#define IDC_TERRAIN_CURRENT_DIR         1022
#define IDC_TERRAIN_DIR_LIST            1023
#define IDC_TERRAIN_SIZE_SLIDER         1024
#define IDC_TERRAIN_SIZE_EDIT           1025
#define IDC_TERRAIN_STRENGTH_SLIDER     1026
#define IDC_TERRAIN_STRENGTH_EDIT       1027
#define IDC_TERRAIN_HEIGHT_SLIDER       1028
#define IDC_TERRAIN_HEIGHT_EDIT         1029
#define IDC_TERRAIN_FALLOFF_LINEAR      1030
#define IDC_TERRAIN_FALLOFF_CURVE       1031
#define IDC_TERRAIN_ABSOLUTEHEIGHT      1032
#define IDC_TERRAIN_WIREFRAME           1033
#define IDC_TERRAIN_FALLOFF_FLAT        1034
#define IDC_TERRAIN_FILTERS_LIST        1035
#define IDC_TERRAIN_CUT                 1036
#define IDC_TERRAIN_REPAIR              1037
#define IDC_OPTIONS_SHELL_SHOWALL       1038
#define IDC_OPTIONS_SHELL_GAMEVISIBILITY 1039
#define IDC_OPTIONS_SCENERY_SHOW        1040
#define IDC_OPTIONS_SCENERY_WIREFRAME   1041
#define IDC_OPTIONS_TERRAIN_SHOW        1042
#define IDC_OPTIONS_TERRAIN_WIREFRAME   1043
#define IDC_OPTIONS_LIGHTING_STANDARD   1044
#define IDC_OPTIONS_LIGHTING_DYNAMIC    1045
#define IDC_OPTIONS_LIGHTING_SPECULAR   1046
#define IDC_OPTIONS_SHOW_TREE           1047
#define IDC_OPTIONS_BSP_NORMAL          1048
#define IDC_OPTIONS_BSP_CUSTOM          1049
#define IDC_OPTIONS_FARPLANE_SLIDER     1050
#define IDC_OPTIONS_FARPLANE_EDIT       1051
#define IDC_OPTIONS_SNAPS_X             1052
#define IDC_OPTIONS_SNAPS_Y             1053
#define IDC_OPTIONS_SNAPS_Z             1054
#define IDC_OPTIONS_SNAPS_ANGLE         1055
#define IDC_OPTIONS_SHELLSNAPS          1056
#define IDC_OPTIONS_UNITSNAPS           1057
#define IDC_OPTIONS_POINTONESNAPS       1058
#define IDC_OPTIONS_BSP_ALL             1059
#define IDC_OPTIONS_CAMERAHEIGHT_SLIDER 1060
#define IDC_OPTIONS_CAMERAHEIGHT_EDIT   1061
#define IDC_SCENE_COLOUR_RED            1062
#define IDC_SCENE_COLOUR_GREEN          1063
#define IDC_SCENE_COLOUR_BLUE           1064
#define IDC_SCENE_COLOURBOX             1065
#define IDC_SCENE_COLOUR_BLUE_STATIC    1066
#define IDC_SCENE_COLOUR_GREEN_STATIC   1067
#define IDC_SCENE_COLOUR_RED_STATIC     1068
#define IDC_SCENE_LIGHT_MULTIPLIER      1069
#define IDC_PROJECT_CONNECT             1070
#define IDC_PROJECT_COMMIT_MESSAGE      1071
#define IDC_PROJECT_COMMIT_KEEPLOCKS    1072
#define IDC_PROJECT_COMMIT_ALL          1073
#define IDC_PROJECT_DISCARD_KEEPLOCKS   1074
#define IDC_PROJECT_DISCARD_ALL         1075
#define IDC_PROJECT_SETTINGS            1076
#define IDC_ERROR_LIST                  1077
#define IDC_ERRORS_LIST                 1078
#define IDC_OPTIONS_TIMEOFDAY_EDIT      1079
#define IDC_OPTIONS_TIMEOFDAY_SLIDER    1080
#define IDC_OPTIONS_REMEMBER_SELECTION_FILTER 1081
#define IDC_SCENE_TREE                  1082
#define IDC_DIALOG_ACTION_CURRENT       1083
#define IDC_OPTIONS_READ_ONLY_MODE      1084
#define IDC_DIALOG_ACTION_DELETE        1085
#define IDC_DIALOG_ACTION_EVENT         1086
#define IDC_DIALOG_ACTION_ACTION        1087
#define IDC_DIALOG_ACTION_ADD           1088
#define IDC_DIALOG_ACTION_CHANGE        1089
#define IDC_SKYDOME_LIST                1090
#define IDC_PROJECT_MAP_ALPHA_SLIDER    1091
#define IDC_INFO                        1092
#define IDC_PAGE_TERRAIN_ADJUST_MASK_BUTTON 1093
#define IDC_TODFILE_BTN                 1094
#define IDC_PAGE_TERRAIN_SIZE_BUTTON    1095
#define IDC_WEATHER_RESETALL            1096
#define IDC_WEATHER_RENAME              1096
#define IDC_NEWTODFILE_BTN              1097
#define IDC_PAGE_TERRAIN_FALLOFF_BUTTON 1098
#define IDC_WEATHER_DEFAULT             1098
#define IDC_HIST_UPDATE                 1099
#define IDC_WEATHER_SKYBOX_ADD          1100
#define IDC_RANDROTX_RESET              1101
#define IDC_ADDCOLOR_BTN                1102
#define IDC_SIZERANGE                   1103
#define IDC_NEWSPACE_BROWSE             1104
#define IDC_WEATHERSETTINGSSTATIC       1105
#define IDC_WEATHERSETTINGS_STATIC      1105
#define IDC_RANDROTY_RESET              1106
#define IDC_STRENGTHRANGE               1107
#define IDC_PROPSHEET_OPTION_PLACEHOLDER 1108
#define IDC_RANDROTZ_RESET              1109
#define IDC_HEIGHTRANGE                 1110
#define IDC_BUTTON2                     1111
#define IDC_SETTINGSFILE_BTN            1112
#define IDC_PAGE_TERRAIN_YAW_ANGLE_BUTTON 1113
#define IDC_DUMMYHIT                    1114
#define IDC_PAGE_TERRAIN_PITCH_ANGLE_BUTTON 1115
#define IDC_RANDSCAX_RESET              1116
#define IDC_PAGE_TERRAIN_ROLL_ANGLE_BUTTON 1117
#define IDC_DELCOLOR_BTN                1118
#define IDC_PROJECT_CANCEL_BTN          1119
#define IDC_EDIT_PLACEMENT_SETTINGS     1120
#define IDC_OBJECTS_EDIT_PLACEMENT_SETTINGS 1121
#define IDC_WEATHER_SETDEFAULTS         1122
#define IDC_WEATHER_ADD                 1122
#define IDC_RANDSCAY_RESET              1123
#define IDC_STATIC_RANGE                1124
#define IDC_MESH_ACTION                 1125
#define IDC_SPACE                       1126
#define IDC_WIDTH                       1127
#define IDC_HEIGHT                      1128
#define IDC_PROGRESS1                   1129
#define IDC_SPACE_PATH                  1130
#define IDC_LIMITCONTROL                1131
#define IDC_MINEDIT                     1132
#define IDC_MAXEDIT                     1133
#define IDC_SUNANGLE_EDIT               1134
#define IDC_MOONANGLE_EDIT              1135
#define IDC_RANDROTY_MIN                1136
#define IDC_RANDPRESETS                 1137
#define IDC_RANDROTY_MAX                1138
#define IDC_RANDROTZ_MIN                1139
#define IDC_RANDROTZ_MAX                1140
#define IDC_RANDSCAY_MIN                1141
#define IDC_RANDSCAY_MAX                1142
#define IDC_RANDSCAZ_MIN                1143
#define IDC_RANDSCAZ_MAX                1144
#define IDC_RANDSCA_LINK                1145
#define IDC_RANDROT_LINK                1146
#define IDC_RANDPRESETSLABEL            1147
#define IDC_RANDROT_GRP                 1148
#define IDC_RANDSCA_GRP                 1149
#define IDC_RANDROT_LINKUP              1150
#define IDC_RANDROT_LINKDOWN            1151
#define IDC_RANDSCA_LINKUP              1152
#define IDC_RANDSCA_LINKDOWN            1153
#define IDC_SEP2                        1154
#define IDC_SEP1                        1155
#define IDC_COLORTIMELINE               1156
#define IDC_COLORPICKER                 1157
#define IDC_SEP3                        1158
#define IDC_SEP4                        1159
#define IDC_TIMEOFDAY_EDIT              1160
#define IDC_TIMEOFDAY_SLIDER            1161
#define IDC_SUNANIM_BTN                 1162
#define IDC_AMBANIM_BTN                 1163
#define IDC_CREATEANIM_BTN              1164
#define IDC_REMOVEANIM_BTN              1165
#define IDC_R_EDIT                      1166
#define IDC_G_EDIT                      1167
#define IDC_B_EDIT                      1168
#define IDC_MIEAMOUNT                   1169
#define IDC_TURBOFFS                    1170
#define IDC_VERTHEIGHTEFFECT            1171
#define IDC_TURBFACTOR                  1172
#define IDC_SUNHEIGHTEFFECT             1173
#define IDC_POWER                       1174
#define IDC_SEP5                        1175
#define IDC_SB_GRAD_EDIT                1176
#define IDC_SB_GRAD_BTN                 1177
#define IDC_SEP6                        1178
#define IDC_ADDSKYDOME_BTN              1179
#define IDC_CLEARSKYDOME_BTN            1180
#define IDC_RANGER                      1181
#define IDC_MIEAMOUNT_SLIDER            1182
#define IDC_PROJECT_VERSIONCONTROL_GROUP 1183
#define IDC_TURBFACTOR_SLIDER           1184
#define IDC_TERIMP_IMPORT_GROUP         1185
#define IDC_BUTTON3                     1186
#define IDC_PAGE_TERRAIN_TEXS_PER_CHUNK_BUTTON 1187
#define IDC_BUTTON4                     1188
#define IDC_PAGE_TERRAIN_CRUNCH_GO_BUTTON 1189
#define IDC_POWER_SLIDER                1190
#define IDC_MINLIMIT                    1191
#define IDC_MAXLIMIT                    1192
#define IDC_CALCULATEDMAP               1193
#define IDC_OBJECTS_SELECTION_FILTER    1194
#define IDC_OBJECTS_SELECT_PLACEMENT_SETTING 1195
#define IDC_OBJECTS_LIGHTING_STANDARD   1196
#define IDC_OBJECTS_LIGHTING_SPECULAR   1197
#define IDC_OBJECTS_LIGHTING_DYNAMIC    1198
#define IDC_OBJECTS_COORDS_WORLD        1199
#define IDC_OBJECTS_COORDS_LOCAL        1200
#define IDC_OBJECTS_COORDS_VIEW         1201
#define IDC_OBJECTS_LOCK_FREE           1202
#define IDC_OBJECTS_LOCK_TERRAIN        1203
#define IDC_OBJECTS_LOCK_OBSTACLE       1204
#define IDC_TERIMP_IMPORT_FILE          1205
#define IDC_TERIMP_PLACE_BTN            1206
#define IDC_TERIMP_BROWSE_BTN           1207
#define IDC_TERIMP_EXPORT_BTN           1208
#define IDC_TERIMP_FILE_STATIC          1209
#define IDC_TERIMP_MODE_CB              1210
#define IDC_TERIMP_MAP_ALPHA_SLIDER     1211
#define IDC_TERIMP_ACTIONTB             1212
#define IDC_TERIMP_ANTICLOCKWISE_BTN    1213
#define IDC_TERIMP_CLOCKWISE_BTN        1214
#define IDC_TERIMP_FLIPX_BTN            1215
#define IDC_TERIMP_FLIPY_BTN            1216
#define IDC_TERIMP_FLIPH_BTN            1217
#define IDC_TERIMP_RECALCCLR_BTN        1218
#define IDC_TERIMP_MIN_EDIT             1219
#define IDC_TERIMP_MIN_SLIDER           1220
#define IDC_TERIMP_MAX_EDIT             1221
#define IDC_TERIMP_MAX_SLIDER           1222
#define IDC_TERIMP_STRENGTH_EDIT        1223
#define IDC_TERIMP_STRENGTH_SLIDER      1224
#define IDC_TERIMP_CANCEL_BTN           1225
#define IDC_TERIMP_HANDDRAWN_GROUP      1226
#define IDC_TERIMP_HEIGHT_SLIDER        1227
#define IDC_RAWIMP_LITTLEENDIAN         1232
#define IDC_RAWIMP_BIGENDIAN            1233
#define IDC_RAWIMP_FILENAME             1234
#define IDC_RAWIMP_BMP                  1235
#define IDC_RAWIMP_SIZE                 1236
#define IDC_NEWSPACE_WIDTH_KM           1237
#define IDC_NEWSPACE_HEIGHT_KM          1238
#define IDC_SKYDOME_TB                  1239
#define IDC_LUMINANCE                   1240
#define IDC_RANDSCAZ_RESET              1241
#define IDC_RGB                         1242
#define IDC_BUILDTIME                   1243
#define IDC_RED                         1244
#define IDC_GREEN                       1245
#define IDC_BLUE                        1246
#define IDC_SLIDER1                     1247
#define IDC_PAGE_TERRAIN_SIZE_SLIDER    1248
#define IDC_RANGERATIOSLIDER            1249
#define IDC_RANDROTX_RANGE              1251
#define IDC_SUNANGLE_SLIDER             1253
#define IDC_SLIDER                      1255
#define IDC_PROJECT_MIN_SLIDER          1256
#define IDC_RANGERATIO                  1257
#define IDC_RANDROTY_RANGE              1258
#define IDC_MOONANGLE_SLIDER            1259
#define IDC_TERIMP_ABS_CB               1260
#define IDC_HIST_AUTOUPDATE             1261
#define IDC_CHANGESPACE                 1262
#define IDC_RANDROTX_CHK                1263
#define IDC_RANDSCA_UNI                 1264
#define IDC_OBJECTS_DRAG_ON_SELECT      1265
#define IDC_PLAYER_PREVIEW_MODE         1266
#define IDC_RANDSCAX_RANGE              1267
#define IDC_CHECK2                      1268
#define IDC_OBJECTS_LOCK_TO_GRID        1269
#define IDC_RANDSCAY_RANGE              1270
#define IDC_RANDSCA_CHK                 1271
#define IDC_STATIC_LUM                  1272
#define IDC_RANDROTZ_RANGE              1273
#define IDC_STATIC_RGB                  1274
#define IDC_RANDSCAX_RANGE3             1275
#define IDC_RANDSCAZ_RANGE              1276
#define IDC_TERRAIN_FILE_LIST           1277
#define IDC_SCENE_PROPERTYLIST          1278
#define IDC_OPTIONS_BSP_DYNAMIC         1279
#define IDC_OPTIONS_FARPLANE_SLIDER2    1280
#define IDC_PROJECT_SELECTION_LOCK      1281
#define IDC_SCENE_COLOUR_BLUE_STATIC2   1282
#define IDC_SCENE_LIGHT_MULTIPLIER_STATIC 1283
#define IDC_OPTIONS_REMEMBER_SELECTION_FILTER2 1284
#define IDC_SB_LIST                     1285
#define IDC_HOTKEY1                     1286
#define IDC_SPACE2                      1287
#define IDC_TODFILE_EDIT                1288
#define IDC_EDITSLAVE                   1289
#define IDC_RANDROTX_MIN                1290
#define IDC_NEWPLACEMENTTEXT            1291
#define IDC_HOURLENGTH                  1292
#define IDC_RANDROTX_MAX                1293
#define IDC_STARTTIME                   1294
#define IDC_RANDSCAX_MIN                1295
#define IDC_RANDSCAX_MAX                1296
#define IDC_SUN_COLORS                  1297
#define IDC_SUN_COLORS_PICKER           1298
#define IDC_TURBOFFS_SLIDER             1299
#define IDC_VERTHEIGHTEFFECT_SLIDER     1300
#define IDC_SUNHEIGHTEFFECT_SLIDER      1301
#define IDC_SLIDER7                     1302
#define IDC_OBJECTS_COORD_FILTER        1303
#define IDC_OBJECTS_SELECTION_FILTER2   1304
#define IDC_SKYFILE_EDIT                1305
#define IDC_SKYFILE_BTN                 1306
#define IDC_NEWSKYFILE_BTN              1308
#define IDC_TEXTURESINCHUNK             1309
#define IDC_WAITDLG_INFO                1310
#define IDC_PROJECT_UPDATE              1311
#define IDC_SAVE                        1312
#define IDC_CONTINUE                    1313
#define IDC_PAGE_TERRAIN_SIZE_EDIT      1314
#define IDC_PAGE_TERRAIN_FALLOFF_EDIT   1315
#define IDC_PAGE_TERRAIN_STRENGTH_EDIT  1316
#define IDC_PAGE_TERRAIN_YAW_ANGLE_EDIT 1317
#define IDC_PAGE_TERRAIN_PITCH_ANGLE_EDIT 1318
#define IDC_PAGE_TERRAIN_ROLL_ANGLE_EDIT 1319
#define IDC_PAGE_TERRAIN_TEXS_PER_CHUNK_EDIT 1320
#define IDC_PAGE_TERRAIN_UTILING_EDIT   1321
#define IDC_PAGE_TERRAIN_VTILING_EDIT   1322
#define IDC_PAGE_TERRAIN_CRUNCH_FROM_EDIT 1323
#define IDC_PAGE_TERRAIN_CRUNCH_TO_EDIT 1324
#define IDC_PAGE_TERRAIN_CURRENT_IMAGE  1325
#define IDC_PAGE_TERRAIN_ACTIVE_TEX_SEPARATOR 1326
#define IDC_PAGE_TERRAIN_TEX_MANAGE_SEPARATOR 1327
#define IDC_PAGE_TERRAIN_TEXTURES_CHUNK_SEPARATOR 1328
#define IDC_MSG_LIST                    1329
#define IDC_MSG_SHOW_DATE               1330
#define IDC_MSG_SHOW_TIME               1331
#define IDC_MSG_SHOW_PRIORITY           1332
#define IDC_MSG_ERROR                   1333
#define IDC_MSG_WARNING                 1334
#define IDC_MSG_NOTICE                  1335
#define IDC_MSG_INFO                    1336
#define IDC_PAGE_TERRAIN_MASK_SEPARATOR 1337
#define IDC_PAGE_TERRAIN_HEIGHT_MASK_BUTTON 1338
#define IDC_PAGE_TERRAIN_HEIGHT_MIN_EDIT 1339
#define IDC_PAGE_TERRAIN_HEIGHT_MAX_EDIT 1340
#define IDC_PAGE_TERRAIN_SLOPE_MASK_BUTTON 1341
#define IDC_PAGE_TERRAIN_SLOPE_MIN_EDIT 1342
#define IDC_PAGE_TERRAIN_SLOPE_MAX_EDIT 1343
#define IDC_PAGE_TERRAIN_HEIGHT_FUZ_EDIT 1344
#define IDC_PAGE_TERRAIN_SLOPE_FUZ_EDIT 1345
#define IDC_DEFTEX_IMAGE                1346
#define IDC_DEFTEX_BROWSE               1347
#define IDC_DEFTEX_PATH                 1348
#define IDC_PAGE_TEXNAME_STATIC         1349
#define IDC_CHUNK_TEXTURE_CHUNK         1350
#define IDC_CHUNK_TEXTURE_GOTO          1351
#define IDD_PAGE_OPTIONS_NAVIGATION     1352
#define IDC_OPTIONS_LOCATION_LIST       1354
#define IDC_OPTIONS_POS_X               1355
#define IDC_OPTIONS_POS_Y               1356
#define IDC_OPTIONS_POS_Z               1357
#define IDC_OPTIONS_CHUNK               1358
#define IDC_OPTIONS_POS_MOVE            1359
#define IDC_OPTIONS_CHUNK_MOVE          1360
#define IDC_OPTIONS_LOCATION_ADD        1361
#define IDC_OPTIONS_LOCATION_REMOVE     1362
#define IDC_OPTIONS_LOCATION_MOVE       1363
#define IDC_OPTIONS_LOCATION_RENAME     1365
#define IDC_OPTIONS_LOCATION_UPDATE     1366
#define IDC_PROPERTIES_LIST             1367
#define IDC_MSG_ASSETS                  1368
#define IDC_CHUNK_TEXTURES_SHOW         1375
#define IDC_CHUNK_TEXTURES_AUTOTRACK    1376
#define IDC_STATISTICS_GRP              1383
#define IDC_UNLOADED_TEXT               1384
#define IDC_UNLOADED_NUM                1385
#define IDC_LOADED_TEXT                 1386
#define IDC_LOADED_NUM                  1387
#define IDC_NEEDSSHADOW_TEXT            1388
#define IDC_NEEDSSHADOW_NUM             1389
#define IDC_DONESHADOW_TEXT             1390
#define IDC_DONESHADOW_NUM              1391
#define IDC_UNLOADED_CLR                1392
#define IDC_LOADED_CLR                  1393
#define IDC_NEEDSSHADOW_CLR             1394
#define IDC_DONESHADOW_CLR              1395
#define IDC_PAGE_TERRAIN_BROWSE_MASK_BUTTON 1396
#define IDC_PAGE_TERRAIN_MASK_PLACE_BUTTON 1397
#define IDC_OPTIONS_GROUP               1404
#define IDC_PROJECTVIEW_CB              1405
#define IDC_FRUSTUM_CB                  1406
#define IDC_UNLOADABLE_CB               1407
#define IDC_MOUSEPOS                    1408
#define IDC_CHUNKID                     1409
#define IDC_CHUNKS_CB                   1413
#define IDC_GRID_CB                     1414
#define IDC_NEWSPC_CREATE_LEGACY        1415
#define IDC_PAGE_TERRAIN_PITCH_ANGLE_SLIDER 1416
#define IDC_PAGE_TERRAIN_FALLOFF_SLIDER 1417
#define IDC_PAGE_TERRAIN_ROLL_ANGLE_SLIDER 1418
#define IDC_PAGE_TERRAIN_UTILING_SLIDER 1419
#define IDC_PAGE_TERRAIN_STRENGTH_SLIDER 1420
#define IDC_PAGE_TERRAIN_YAW_ANGLE_SLIDER 1421
#define IDC_PAGE_TERRAIN_VTILING_SLIDER 1422
#define IDC_PAGE_TERRAIN_IMPORTED_MASK_BUTTON 1423
#define IDC_PAGE_TERRAIN_OVERLAY_MASK_BUTTON 1424
#define IDC_PAGE_TERRAIN_RESET_PROJ_BUTTON 1425
#define IDC_PAGE_TERRAIN_MASK_IMAGE     1426
#define IDC_PAGE_TERRAIN_OPACITY_SLIDER 1427
#define IDC_PAGE_TERRAIN_MODETB         1428
#define IDC_PAGE_TEXTURE_LATCH          1429
#define IDC_PAGE_TERRAIN_OPACITY_EDIT   1430
#define IDC_PAGE_TERRAIN_CURRENT_PROJECTION 1431
#define IDC_PAGE_TERRAIN_SIZE_SEPARATOR 1432
#define IDC_HEIGHTMAP_SIZE              1434
#define IDC_NORMALMAP_SIZE              1435
#define IDC_HOLEMAP_SIZE                1436
#define IDC_SHADOWMAP_SIZE              1437
#define IDC_BLENDMAP_SIZE               1438
#define IDC_CONV_HEIGHTMAP_SIZE         1441
#define IDC_CONV_NORMALMAP_SIZE         1442
#define IDC_CONV_HOLEMAP_SIZE           1443
#define IDC_CONV_SHADOWMAP_SIZE         1444
#define IDC_CONV_BLENDMAP_SIZE          1445
#define IDC_SHADER_PROGRESS_BAR         1446
#define IDC_SHADER_LOADING_STATIC       1447
#define IDC_GRAPHICS_SETTINGS_MSG       1448
#define IDC_RESIZE_BLENDMAP_SIZE        1449
#define IDC_RESIZEMAP_CURSIZE           1450
#define IDC_ICON_WARNING                1451
#define IDC_PAGE_TEX_DIM                1452
#define IDC_PAGE_TEX_SIZE               1453
#define IDC_PAGE_TERRAIN_MASK_ACTIONTB  1454
#define IDC_PAGE_TERRAIN_MASK_STRENGTH_EDIT 1455
#define IDC_PAGE_TERRAIN_MASK_STRENGTH_SLIDER 1456
#define IDC_PAGE_TERRAIN_MASK_SEP1      1458
#define IDC_PAGE_TERRAIN_ANTICLOCKWISE_BTN 1459
#define IDC_PAGE_TERRAIN_CLOCKWISE_BTN  1460
#define IDC_PAGE_TERRAIN_FLIPX_BTN      1461
#define IDC_PAGE_TERRAIN_FLIPY_BTN      1462
#define IDC_PAGE_TERRAIN_FLIPH_BTN      1463
#define IDC_PAGE_TERRAIN_LINKUP         1465
#define IDC_PAGE_TERRAIN_LINKDOWN       1466
#define IDC_PAGE_TERRAIN_LINK           1467
#define IDC_TEXLOD_START_EDIT           1468
#define IDC_TEXLOD_START_SLIDER         1469
#define IDC_TEXLOD_DIST_EDIT            1470
#define IDC_TEXLOD_DIST_SLIDER          1471
#define IDC_TEXLOD_PRELOAD_EDIT         1472
#define IDC_TEXLOD_PRELOAD_SLIDER       1473
#define IDC_PAGE_TERRAIN_TEXMASK_BUTTON 1474
#define IDC_PAGE_TERRAIN_TEXMASK_PROJ_BUTTON 1475
#define IDC_PAGE_TERRAIN_TEXMASK_INV_BUTTON 1476
#define IDC_PAGE_TERRAIN_TEXMASK_YAW_EDIT 1477
#define IDC_PAGE_TERRAIN_TEXMASK_PITCH_EDIT 1478
#define IDC_PAGE_TERRAIN_TEXMASK_ROLL_EDIT 1479
#define IDC_PAGE_TERRAIN_MASKTEX_IMAGE  1480
#define IDC_PAGE_TERRAIN_TEXMASK_UTILING_EDIT 1481
#define IDC_PAGE_TERRAIN_TEXMASK_VTILING_EDIT 1482
#define IDC_NOISE_IMG                   1483
#define IDC_WAVELEN_SLIDER1             1484
#define IDC_WAVELEN_SLIDER2             1485
#define IDC_WAVELEN_SLIDER3             1486
#define IDC_WAVELEN_SLIDER4             1487
#define IDC_WAVELEN_SLIDER5             1488
#define IDC_WAVELEN_SLIDER6             1489
#define IDC_WAVELEN_SLIDER7             1490
#define IDC_WAVELEN_SLIDER8             1491
#define IDC_WAVELEN_EDIT1               1492
#define IDC_WAVELEN_EDIT2               1493
#define IDC_WAVELEN_EDIT3               1494
#define IDC_WAVELEN_EDIT4               1495
#define IDC_WAVELEN_EDIT5               1496
#define IDC_WAVELEN_EDIT6               1497
#define IDC_WAVELEN_EDIT7               1498
#define IDC_WAVELEN_EDIT8               1499
#define IDC_WEIGHT_SLIDER1              1500
#define IDC_WEIGHT_SLIDER2              1501
#define IDC_WEIGHT_SLIDER3              1502
#define IDC_WEIGHT_SLIDER4              1503
#define IDC_WEIGHT_SLIDER5              1504
#define IDC_WEIGHT_SLIDER6              1505
#define IDC_WEIGHT_SLIDER7              1506
#define IDC_WEIGHT_SLIDER8              1507
#define IDC_WEIGHT_EDIT1                1508
#define IDC_WEIGHT_EDIT2                1509
#define IDC_WEIGHT_EDIT3                1510
#define IDC_WEIGHT_EDIT4                1511
#define IDC_WEIGHT_EDIT5                1512
#define IDC_WEIGHT_EDIT6                1513
#define IDC_WEIGHT_EDIT7                1514
#define IDC_WEIGHT_EDIT8                1515
#define IDC_SEED_EDIT1                  1516
#define IDC_SEED_EDIT2                  1517
#define IDC_SEED_EDIT3                  1518
#define IDC_SEED_EDIT4                  1519
#define IDC_SEED_EDIT5                  1520
#define IDC_SEED_EDIT6                  1521
#define IDC_SEED_EDIT7                  1522
#define IDC_SEED_EDIT8                  1523
#define IDC_MIN_STRENGTH_UNITS          1524
#define IDC_MAX_STRENGTH_UNITS          1525
#define IDC_MIN_STRENGTH_EDIT           1526
#define IDC_MAX_STRENGTH_EDIT           1527
#define IDC_MIN_STRENGTH_SLIDER         1528
#define IDC_MAX_STRENGTH_SLIDER         1529
#define IDC_PAGE_TERRAIN_NOISE_MASK_BUTTON 1530
#define IDC_MIN_SAT_SLIDER              1531
#define IDC_PAGE_TERRAIN_NOISE_SETUP_BUTTON 1532
#define IDC_MIN_SAT_EDIT                1533
#define IDC_MIN_SAT_UNITS               1534
#define IDC_MAX_SAT_SLIDER              1535
#define IDC_MAX_SAT_EDIT                1536
#define IDC_MAX_SAT_UNITS               1537
#define IDC_OK                          1539
#define IDC_PAGE_TERRAIN_LIMIT_LAYERS_CB 1540
#define IDC_PAGE_TERRAIN_LIMIT_LAYERS_EDIT 1541
#define IDC_TERRAIN_FALLOFF_AVERAGE     1542
#define IDC_UNDOWARN_DONT_REPEAT        1543
#define IDC_SKYBOXES_TB                 1545
#define IDC_WEATHER_SYSTEMS_LIST        1546
#define IDC_SKY_BOXES_LIST              1547
#define IDC_WEATHER_EXCLUDE             1548
#define IDC_WEATHER_SKYBOX_CLEAR        1549
#define IDC_WEATHER_REMOVE              1550
#define IDC_SKY_BOXES_STATIC            1552
#define IDC_SKY_BOXES_STATIC2           1552
#define IDC_PROPERTIES_STATIC           1553
#define IDC_PROPERTIES_STATIC2          1554
#define IDB_SEARCHMAGNIFIER             1555
#define IDC_SEARCHMAGNIFIER             1556
#define IDB_SEARCHCLOSE                 1557
#define IDC_SEARCHCLOSE                 1558
#define IDB_CHECK_OFF                   1558
#define IDC_OPTIONS_LOCATION_SEARCH     1559
#define IDC_SB_SEARCH                   1560
#define IDC_SB_SEARCHBK                 1561
#define IDC_SB_GROUP_BY                 1562
#define IDC_SB_GROUP_BY_LABEL           1563
#define IDC_SB_STATUS                   1564
#define IDC_STRING_INPUT_LABEL          1565
#define IDC_STRING_INPUT_EDIT           1566
#define IDC_SKYBOX_UP                   1567
#define IDC_SKYBOX_DOWN                 1568
#define IDC_SKYBOX_DEL                  1569
#define IDC_SKYDOME_UP                  1570
#define IDC_SKYDOME_DOWN                1571
#define IDC_SKYDOME_DEL                 1572
#define IDC_GRAPH_VIEW                  1574
#define IDC_PP_NEW_CHAIN                1575
#define IDC_PP_RENAME_CHAIN             1576
#define IDC_PP_DELETE_CHAIN             1577
#define IDC_PP_SAVE_CHAIN               1578
#define IDC_PP_DUPLICATE_CHAIN          1579
#define IDC_PP_DISCARD_CHANGES          1580
#define IDC_PP_CHAIN_LIST               1581
#define IDC_POST_PROC_PROPERTIES_LIST   1582
#define IDC_PP_PROPERIES_LABEL          1583
#define IDC_PP_DELETE_ALL               1584
#define IDC_PP_3D_PREVIEW               1585
#define IDC_PP_GRAPH_INFO               1586
#define IDC_PPGRAPH_VERT_SB             1587
#define IDC_PPGRAPH_HORZ_SB             1588
#define IDC_PP_LAYOUT                   1589
#define IDC_SB_WORKING_ANIM             1590
#define IDC_PP_ZOOM_IN                  1591
#define IDC_PP_ZOOM_OUT                 1592
#define IDC_PP_NOZOOM                   1593
#define IDC_PP_PROFILE                  1594
#define ID_BUTTON_MOVESPEED1            32771
#define ID_BUTTON_MOVESPEED2            32772
#define ID_BUTTON_MOVESPEED3            32773
#define ID_BUTTON_MOVESPEED4            32774
#define ID_BUTTON_BG_UPDATE             32775
#define ID_BUTTON_QUICKSAVE             32776
#define ID_BUTTON_FULLSAVE              32777
#define ID_BUTTON_LOAD_ALL              32778
#define ID_BUTTON_COORD_WORLD           32779
#define ID_BUTTON_COORD_OBJECT          32780
#define ID_BUTTON_COORD_VIEW            32781
#define ID_BUTTON_PLAYER_PREVIEW        32782
#define ID_TOOL_OBJECT                  32783
#define ID_TOOL_TERRAIN_TEXTURE         32784
#define ID_TOOL_TERRAIN_HEIGHT          32785
#define ID_TOOL_TERRAIN_FILTER          32786
#define ID_TOOL_TERRAIN_MESH            32787
#define ID_TOOL_PROJECT                 32788
#define ID_BUTTON_UNDO                  32789
#define ID_BUTTON_REDO                  32790
#define ID_SELECTION_FILTER_PLACEHOLDER 32791
#define ID_TER_PAINT_PAINTMODE          32792
#define ID_TER_PAINT_REPLACEMODE        32793
#define ID_TER_PAINT_EDITMODE           32794
#define ID_TER_PAINT_SAVE_BTN           32795

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        295
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1594
#define _APS_NEXT_SYMED_VALUE           252
#endif
#endif
