//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by modeleditor.rc
//
#define IDR_MANIFEST_LEGACY             1
#define ID_REMOVE_TEXTURE_FEED          3
#define IDC_REMOVE_TEXTURE_FEED         3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_SPLASH                      101
#define ID_INDICATOR_TRIANGLES          101
#define ID_INDICATOR_NODES              102
#define ID_INDICATOR_TETXURE_MEM        103
#define ID_INDICATOR_FRAMERATE          104
#define ID_INDICATOR_BLENDBONE_NODES    105
#define IDR_MAINFRAME                   128
#define IDR_ModelEditorTYPE             129
#define IDB_SPLASH                      131
#define IDB_ABOUT                       132
#define IDB_ABOUTBOX                    132
#define IDB_TOOLBAR_HOT                 133
#define IDB_TOOLBAR_COLD                134
#define IDD_DISPLAY                     135
#define IDD_ANIMATIONS                  137
#define IDB_SEARCH                      139
#define IDB_CANCEL                      140
#define IDB_ANIM_TOOLBAR                143
#define IDI_ANIMATION                   146
#define IDI_ANIMATIONS                  146
#define IDB_BITMAP2                     147
#define IDI_ICON1                       148
#define IDI_DISPLAY                     148
#define IDD_ACTIONS                     149
#define IDB_ACT_TOOLBAR                 150
#define IDD_CHOOSE_ANIM                 150
#define IDI_ACTIONS                     152
#define IDD_DIALOG1                     154
#define IDD_EMPTY                       154
#define IDD_LOD                         155
#define IDI_ICON2                       156
#define IDI_LOD                         156
#define IDD_LIGHTS                      156
#define IDB_LOD_PAT_1                   157
#define IDI_LOD1                        157
#define IDI_LIGHTS                      157
#define IDB_LOD_PAT_2                   158
#define IDB_BITMAP5                     159
#define IDB_LOD_PAT_3                   159
#define IDD_PREFS                       162
#define IDD_MATERIALS                   163
#define IDI_MATERIALS                   164
#define IDD_NEW_TINT                    165
#define IDI_LOD2                        165
#define IDI_OBJECT                      165
#define IDD_CHOOSE_ANIM1                166
#define IDD_CREATE_ACT                  166
#define IDI_OBJECT1                     166
#define IDI_ERRORS                      166
#define IDC_CURSOR1                     166
#define ID_OK                           166
#define IDD_OBJECT                      167
#define IDD_LOADING                     168
#define IDD_ANIMATIONS1                 169
#define IDD_EXPLORER                    169
#define IDD_ERRORS                      169
#define IDD_ACT_TRIGGER                 170
#define IDD_KEY_CUTS                    171
#define IDD_SHORTCUTS_HMTL              171
#define IDD_SHORTCUTS                   171
#define IDD_TEXTURE_FEED                172
#define IDD_LOAD_ERROR                  173
#define IDB_MINUS                       175
#define IDB_BITMAP3                     176
#define IDB_PLUS                        176
#define IDD_SHADER_LOADING              177
#define IDC_DISPLAY_GENERAL_BOX         1000
#define IDC_SHOW_AXES                   1001
#define IDC_CHECK_FOR_SPARKLES          1002
#define IDC_SHOW_BLOOM                  1003
#define IDC_SHOW_SHIMMER                1004
#define IDC_DISPLAY_MODEL_BOX           1005
#define IDC_SHOW_MODEL                  1006
#define IDC_SHOW_SKELETON               1007
#define IDC_SHOW_WIREFRAME              1008
#define IDC_SHOW_BSP                    1009
#define IDC_SHOW_BOUNDING_BOX           1010
#define IDC_SHOW_PORTALS                1011
#define IDC_GROUND_MODEL                1012
#define IDC_CENTRE_MODEL                1013
#define IDC_SHADOWING                   1014
#define IDC_DISPLAY_BKG_BOX             1015
#define IDC_DISPLAY_BKG                 1016
#define IDC_DISPLAY_CHOOSE_BKG_COLOUR   1017
#define IDC_DISPLAY_CHOOSE_FLOOR_TEXTURE 1018
#define IDC_DISPLAY_TIME_OF_DAY_BOX     1019
#define IDC_DISPLAY_TIMEOFDAY_BOX       1019
#define IDC_TIMEOFDAY_SLIDER            1020
#define IDC_TIMEOFDAY_TEXT              1021
#define IDC_DISPLAY_FLORA               1022
#define IDC_SHOW_VERTEX_NORMALS         1023
#define IDC_SHOW_HARD_POINTS            1024
#define IDC_SHOW_CUSTOM_HULL            1025
#define IDC_SHOW_EDITOR_PROXY           1026
#define IDC_SHOW_VERTEX_BINORMALS       1027
#define IDC_ENABLE_FOG                  1028
#define IDC_OBJECT_NAME                 1101
#define IDC_OBJECT_THUMBNAIL            1102
#define IDC_OBJECT_BATCH                1103
#define IDC_OBJECT_LIST                 1104
#define IDC_OBJECT_BATCH2               1104
#define IDC_OBJECT_OCCLUDER             1104
#define IDC_OBJECT_KIND                 1105
#define IDC_ACT_TRIGGER_MAX             1150
#define IDC_ACT_CANCEL_MAX              1151
#define IDC_TEXTURE_FEED_NAME           1152
#define IDC_ACT_BLEND_IN                1153
#define IDC_ACT_BLEND_OUT               1154
#define IDC_ACT_BLEND_IN_SLIDER         1155
#define IDC_ACT_BLEND_OUT_SLIDER        1156
#define IDC_ACT_TRIGGER_FALLING         1157
#define IDC_ACT_CANCEL_FALLING          1158
#define ID_ICON                         1160
#define IDC_BUTTON1                     1161
#define IDC_OBJECT_PROXY_REMOVE         1161
#define IDC_OBJECT_PROXY_SEL            1164
#define IDC_OBJECT_PROXY                1165
#define IDC_ANIM_BLEND_TEXT             1166
#define IDC_ANIM_POSITION_TEXT          1167
#define IDC_ANIM_ROTATION_TEXT          1168
#define IDC_ANIM_SCALE_TEXT             1169
#define IDC_NORMALS_SIZE_SLIDER         1170
#define IDC_ACT_MRU                     1171
#define IDC_SHADER_LOADING_STATIC       1172
#define IDC_SHADER_PROGRESS_BAR         1173
#define IDC_ACT_OWN_TRACK               1174
#define IDC_ANIM_TREE                   1200
#define IDC_ANIM_NAME                   1201
#define IDC_ANIM_SOURCE_OLD             1202
#define IDC_ANIM_FRAME_RATE             1203
#define IDC_ANIM_FRAME                  1204
#define IDC_ANIM_FIRST                  1205
#define IDC_ANIM_LAST                   1206
#define IDC_ANIM_FRAME_RATE_SLIDER      1207
#define IDC_ANIM_NODES_BOX              1208
#define IDC_ANIM_NODES                  1209
#define IDC_ANIM_BLEND                  1210
#define IDC_ANIM_BLEND_SLIDER           1211
#define IDC_ANIM_SEARCH                 1212
#define IDC_ANIM_TOOLBAR                1213
#define IDC_ANIM_FRAME_SLIDER           1214
#define IDC_ANIM_SEARCH_CANCEL          1215
#define IDC_ANIM_REMOVE_BLEND           1216
#define IDC_ANIM_SOURCE                 1217
#define IDC_ANIM_SAVE_FRAME_RATE        1218
#define IDC_ANIM_COMP_BOX               1219
#define IDC_ANIM_COMP_SCALE             1220
#define IDC_ANIM_COMP_POS_SLDR          1221
#define IDC_ANIM_COMP_ROT_SLDR          1222
#define IDC_ANIM_COMP_SCALE_SLDR        1223
#define IDC_ANIM_COMP_POS_PLUS          1224
#define IDC_ANIM_COMP_POS_MINUS         1225
#define IDC_ANIM_COMP_ROT_PLUS          1226
#define IDC_ANIM_COMP_ROT_MINUS         1227
#define IDC_ANIM_COMP_SCALE_PLUS        1228
#define IDC_ANIM_COMP_SCALE_MINUS       1229
#define IDC_ANIM_COMP_TOTAL             1230
#define IDC_ANIM_COMP_TOOLBAR           1231
#define IDC_ANIM_COMP_POS               1232
#define IDC_ANIM_COMP_ROT               1233
#define IDC_ANIM_CHANGE_ANIM            1234
#define IDC_ACT_TOOLBAR                 1300
#define IDC_ACT_NAME                    1301
#define IDC_ACT_ANIM                    1302
#define IDC_ACT_TRACK                   1303
#define IDC_ACT_CHANGE_ANIM             1304
#define IDC_ACT_LOOP                    1305
#define IDC_ACT_MOVE                    1306
#define IDC_ACT_TRIGGER_CAPS_ON_SEL     1307
#define IDC_ACT_IMPACT                  1308
#define IDC_ACT_COORD                   1309
#define IDC_ACT_TRIGGER_CAPS_OFF_SEL    1310
#define IDC_ACT_CANCEL_CAPS_ON_SEL      1311
#define IDC_ACT_TRIGGER_SPEED_MIN       1312
#define IDC_ACT_TRIGGER_SPEED_MAX       1313
#define IDC_ACT_TRIGGER_AUX1_MIN        1314
#define IDC_ACT_TRIGGER_AUX1_MAX        1315
#define IDC_ACT_TRIGGER_YAW_MIN         1316
#define IDC_ACT_TRIGGER_YAW_MAX         1317
#define IDC_ACT_TRIGGER_CAPS_ON         1318
#define IDC_ACT_ONE_SHOT                1319
#define IDC_ACT_TRIGGER_CAPS_OFF        1320
#define IDC_ACT_CANCEL_SPEED_MIN        1321
#define IDC_ACT_CANCEL_SPEED_MAX        1322
#define IDC_ACT_CANCEL_AUX1_MIN         1323
#define IDC_ACT_CANCEL_AUX1_MAX         1324
#define IDC_ACT_CANCEL_YAW_MIN          1325
#define IDC_ACT_CANCEL_YAW_MAX          1326
#define IDC_ACT_CANCEL_CAPS_ON          1327
#define IDC_ACT_CANCEL_CAPS_OFF         1328
#define IDC_ACT_PROMOTE_MOTION          1329
#define IDC_ACT_SCALE_PLAYBACK_SPEED    1330
#define IDC_ACT_FEET_FOLLOW_DIRECTION   1331
#define IDC_ACT_CANCEL_CAPS_OFF_SEL     1332
#define IDC_ACT_CANCEL_AUX1_SLDR        1333
#define IDC_ACT_CANCEL_YAW_SLDR         1334
#define IDC_ACT_MATCH_BOX               1335
#define IDC_ACT_TRIGGER_BOX             1336
#define IDC_ACT_CANCEL_BOX              1337
#define IDC_ACT_TRIGGER_SPEED_SLDR      1338
#define IDC_ACT_TRIGGER_AUX1_SLDR       1340
#define IDC_ACT_CANCEL_SPEED_SLDR       1341
#define IDC_ACT_TRIGGER_YAW_SLDR        1342
#define IDC_LOD_DIST                    1400
#define IDC_LOD_MAX                     1401
#define IDC_LOD_TREE                    1402
#define IDC_LOD_LIST                    1403
#define IDC_LOD_NEW                     1404
#define IDC_LOD_REMOVE                  1405
#define IDC_LOD_CHANGE                  1406
#define IDC_LOD_TOOLBAR                 1407
#define IDC_LOD_MIN                     1408
#define IDC_LOD_DIST_SLIDER             1409
#define IDC_LOD_BAR                     1410
#define IDC_LOD_HIDDEN                  1411
#define IDC_LOD_VIRTUAL_DIST            1412
#define IDC_LOD_DIST_UNIT               1413
#define IDC_LOD_DIST_TITLE              1414
#define IDC_LIGHTS_USE_GAME             1500
#define IDC_TIMEOFDAY_TITLE             1501
#define IDC_LIGHTS_USE_CUSTOM           1502
#define IDC_LIGHTS_TOOLBAR              1503
#define IDC_LIGHTS_LIST                 1504
#define IDC_LIGHTS_SETUPS               1505
#define IDC_LIGHTS_CAMERA               1506
#define IDC_LIGHTS_MODELS               1507
#define IDC_MATERIALS_TOOLBAR           1600
#define IDC_MATERIALS_MATERIAL          1601
#define IDC_MATERIALS_MATTER            1602
#define IDC_MATERIALS_TINT              1603
#define IDC_MATERIALS_TREE              1604
#define IDC_MATERIALS_FX_LIST           1605
#define IDC_MATERIALS_FX_SEL            1606
#define IDC_MATERIALS_PREVIEW           1607
#define IDC_MATERIALS_PREVIEW_LIST      1608
#define IDC_MATERIALS_PREVIEW_RECT      1609
#define IDC_MATERIALS_TECHNIQUE         1610
#define IDC_MSG_LIST                    1700
#define IDC_MSG_SHOW_DATE               1701
#define IDC_MSG_SHOW_TIME               1702
#define IDC_MSG_SHOW_PRIORITY           1703
#define IDC_MSG_ERROR                   1704
#define IDC_MSG_WARNING                 1705
#define IDC_MSG_NOTICE                  1706
#define IDC_MSG_INFO                    1707
#define IDC_MSG_ASSETS                  1708
#define IDC_PROGRESS_BAR                1800
#define IDC_TRIGGER_LIST                1900
#define IDC_NEW_TINT_NAME               2000
#define IDC_NEW_TINT_FX_CHECK           2001
#define IDC_NEW_TINT_FX_LIST            2002
#define IDC_NEW_TINT_FX_SEL             2003
#define IDC_NEW_TINT_MFM_CHECK          2004
#define IDC_NEW_TINT_MFM_LIST           2005
#define IDC_NEW_TINT_MFM_SEL            2006
#define IDC_PREFS_SHOW_SPLASH_SCREEN    2100
#define IDC_PREFS_LOAD_LAST_MODEL       2101
#define IDC_PREFS_LOAD_LAST_LIGHTS      2102
#define IDC_PREFS_ZOOM_ON_LOAD          2103
#define IDC_PREFS_ANIMATE_ZOOM          2104
#define IDC_PREFS_LOCK_LOD              2105
#define IDC_PREFS_INVERT_MOUSE          2106
#define IDC_PREFS_INVERT_MOUSE2         2107
#define IDC_PREFS_REGEN_BB              2107
#define IDC_SEARCH_BKG                  3000
#define IDC_SEARCH_BUTTON               3001
#define IDC_SEARCH_TEXT                 3002
#define IDC_SEARCH_CANCEL               3003
#define IDC_SEARCH_TREE                 3004
#define IDC_PROPERTIES_LIST             4000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        178
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1175
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
